### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by uoziod** [codrops/RainEffect#2]
Hey guys,
Thank you for this spectacular thing))

So, why not create New-tab Chrome extension with real weather data and possibility to change background?

If you'll create a project for that I'll be glad to contribute.

**Comment by nirajkaushal** [comment]
Hey @uoziod ,
I was also thinking about it and it will be awesome to create Google new tab extension ;-)

**Comment by uoziod** [comment]
I can force it. Create a repo for that, I'll provide a starter.

**Comment by nirajkaushal** [comment]
It is here https://github.com/nirajkaushal/Weather-Chrome-Extenstion

**Comment by nirajkaushal** [comment]
Hey Guys, I have created a chrome extension. Let me know if anybody interested to contribute on it.

some screenshots are below
![weather](https://user-images.githubusercontent.com/8850541/42132994-0e001db4-7d40-11e8-8518-b8c4224385e9.png)
![screenshot 322](https://user-images.githubusercontent.com/8850541/42133180-f646cc92-7d42-11e8-8a91-ce16fad033cf.png)
