### ISSUE TITLE
Can't run locally.

### ISSUE THREAD

**Issue by AM-young-fun** [codrops/RainEffect#4]
```
WebGL: INVALID_VALUE: texImage2D: no image data
Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.
```

**Comment by AM-young-fun** [comment]
How to fix this problem?

**Comment by AM-young-fun** [comment]
Environment:

Mac OSX EI Capitan
Chrome  49.0.2623.112 (64-bit)

**Comment by hrishioa** [comment]
I have the same problem with the same error. Must be my lack of experience, since running with 'gulp connect' works fine.

Perhaps someone could explain why this is happening.

**Comment by AM-young-fun** [comment]
@hrishioa  Hi hrishioa, it's been days and I decide to try 
`gulp connect`.

Since I'm not familiar with gulp... I ran into such an error after `npm install gulp`:

![image](https://cloud.githubusercontent.com/assets/6587734/14976744/e943798e-1140-11e6-9dbc-fbca936619b4.png)

Which gulp version are you using?

**Comment by AM-young-fun** [comment]
No bother... I just forgot to 'npm install'.

**Comment by hrishioa** [comment]
Still not sure what gulp connect is doing that I can't replicate running locally.

**Comment by AM-young-fun** [comment]
@hrishioa  I've seen some threads that claim webgl has some issue with the 'file://' protocol when trying to load textures.
Once you deploy the demo on server it would run correctly.

**Comment by hrishioa** [comment]
@AntiMoron thanks I'll check that out.

**Comment by JasonWandrag** [comment]
it seems to only be a problem on chrome, as firefox and ie11 opens it (although in ie11 it looks quite bad)

**Comment by AM-young-fun** [comment]
You can set up a local server to host the texture file. It's easy to do with `serve`

`npm install -g serve`

closing.
