### ISSUE TITLE
No longer working on Firefox

### ISSUE THREAD

**Issue by Le-future** [codrops/RainEffect#6]
Hello,

I just seen that the effect is no longer working on Firefox ( I get a black screen )

Console error : TypeError: Argument 6 is not valid for any of the 6-argument overloads of WebGLRenderingContext.texImage2D.

**Comment by goranapo** [comment]
i am also getting blackscreen on chrome, windows 10
Working well on internet explorer, edge and chrome on android.
website: http://cryptodesign.eu
__
Uncaught (in promise) TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.
    at u (rain.min.js:7)
    at Object.o [as createTexture] (rain.min.js:7)
    at n.createTexture (rain.min.js:6)
    at s.init (rain.min.js:7)
    at s (rain.min.js:6)
    at s (rain.min.js:6)
    at rain.min.js:6
__

**Comment by yuvarajvemula** [comment]
Ya , I too getting same in Firefox 52 (beta) On Ubutnu 16.04 LTS

**Comment by crnacura** [comment]
Should be fixed with the latest update by @ecrider

**Comment by goranapo** [comment]
It's fixed !

check: 
https://tympanus.net/Development/RainEffect/
https://tympanus.net/Development/RainEffect/index3.html

**Comment by Le-future** [comment]
Perfect!
