### ISSUE TITLE
No longer works in Chrome

### ISSUE THREAD

**Issue by roshansachan** [codrops/RainEffect#7]
Error: Uncaught (in promise) TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.
Shows a black background.

Chrome version:  56.0.2924.87 (64-bit)
OS: OSX 10.9.5
Confirmed does not work on windows.

**Comment by roshansachan** [comment]
As a workaround, I have added a try catch block around the line causing this error.
```
  try{
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, source);
  }catch(e){
    console.log(e);
  }
```

**Comment by crnacura** [comment]
We'll use this workaround for now, thanks! @lbebber, any ideas?

**Comment by ecrider** [comment]
You are doing it wrong. Problem is in function responsible for creating textures (that is ran once, on load), it's trying to push null 'source' variable into updateTexture function. In previous versions of Chrome it returned a warning in console, now it's an error causing a failure.

Proper fix is a simple validation at the end of createTexture function, like this one: 

`	if ( source == null ) {`
`		return texture;`
`	} else {`
`		updateTexture(gl,source);`
`	}`
`	return texture;`

Just make sure updateTexture always get proper variables, but don't even try to make any fancy validation inside it or it will impact performance - textures are created only once on load, then updated all the time, over and over again.

**Comment by goranapo** [comment]
How to use this workaround? 
Or maybe #ecrider can guide us here how to make it the right way ? I am not programmer, just want to fix my website, thanks.

**Comment by ecrider** [comment]
You need to access source files, in src/webgl.js file find function "createTexture", then inside that function replace "updateTexture(gl, source);" (line 88) with first 5 lines of code I wrote in previous comment. Save changes, transform and bundle your sources with gulp, replace minified js in your project and that should do the trick.

**Comment by ecrider** [comment]
I forked this project, added my fix to source, compiled new demo files. Works like a charm.
https://github.com/ecrider/RainEffect

**Comment by midweststudios** [comment]
Thank you @ecrider!

**Comment by nirajkaushal** [comment]
I was also facing same error...but now resolved, Thank you so much @ecrider

**Comment by mythreyan37** [comment]
function u(t, e) {
      t.texImage2D(t.TEXTURE_2D, 0, t.RGBA, t.RGBA, t.UNSIGNED_BYTE, e);      
     }




Note:   Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.        


In Mozilla Firefox and all other browsers will have supported this function, but in chrome, it didn't work... How to resolve this error?
